version: '3.3'

services:
  phpapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    image: php:8.2-apache
    ports:
      - "8181:80"
    environment:
      MYSQL_ROOT_PASSWORD: Baleine12345
      MYSQL_DATABASE: DBALEINE
      MYSQL_USER: UserBaleine
      MYSQL_PASSWORD: Baleine12345
    volumes:
      - ./php:/var/www/html
    networks:
      - lan

  bd:
    image: mysql
    container_name: bd
    environment:
      MYSQL_ROOT_PASSWORD: Baleine12345
      MYSQL_DATABASE: DBALEINE
      MYSQL_USER: UserBaleine
      MYSQL_PASSWORD: Baleine12345
    networks:
      - lan

networks:
  lan:
    external: false
